package main

var seedExercises = []Exercise{
	// Chest
	{Name: "Barbell Bench Press", Category: "Barbell", MuscleGroup: "Chest"},
	{Name: "Incline Barbell Bench Press", Category: "Barbell", MuscleGroup: "Chest"},
	{Name: "Decline Barbell Bench Press", Category: "Barbell", MuscleGroup: "Chest"},
	{Name: "Dumbbell Bench Press", Category: "Dumbbell", MuscleGroup: "Chest"},
	{Name: "Incline Dumbbell Press", Category: "Dumbbell", MuscleGroup: "Chest"},
	{Name: "Dumbbell Flyes", Category: "Dumbbell", MuscleGroup: "Chest"},
	{Name: "Dumbbell Pullover", Category: "Dumbbell", MuscleGroup: "Chest"},
	{Name: "Cable Crossover", Category: "Cable", MuscleGroup: "Chest"},
	{Name: "Cable Chest Press", Category: "Cable", MuscleGroup: "Chest"},
	{Name: "Push-Up", Category: "Bodyweight", MuscleGroup: "Chest"},
	{Name: "Incline Push-Up", Category: "Bodyweight", MuscleGroup: "Chest"},
	{Name: "Knee Push-Up", Category: "Bodyweight", MuscleGroup: "Chest"},
	{Name: "Chest Dip", Category: "Bodyweight", MuscleGroup: "Chest"},
	{Name: "Machine Chest Press", Category: "Machine", MuscleGroup: "Chest"},
	{Name: "Pec Deck", Category: "Machine", MuscleGroup: "Chest"},
	{Name: "Smith Machine Bench Press", Category: "Smith Machine", MuscleGroup: "Chest"},

	// Back
	{Name: "Deadlift", Category: "Barbell", MuscleGroup: "Back"},
	{Name: "Barbell Row", Category: "Barbell", MuscleGroup: "Back"},
	{Name: "T-Bar Row", Category: "Barbell", MuscleGroup: "Back"},
	{Name: "Rack Pull", Category: "Barbell", MuscleGroup: "Back"},
	{Name: "Barbell Shrug", Category: "Barbell", MuscleGroup: "Back"},
	{Name: "Dumbbell Row", Category: "Dumbbell", MuscleGroup: "Back"},
	{Name: "Dumbbell Shrug", Category: "Dumbbell", MuscleGroup: "Back"},
	{Name: "Chest-Supported Row", Category: "Dumbbell", MuscleGroup: "Back"},
	{Name: "Pull-Up", Category: "Bodyweight", MuscleGroup: "Back"},
	{Name: "Chin-Up", Category: "Bodyweight", MuscleGroup: "Back"},
	{Name: "Inverted Row", Category: "Bodyweight", MuscleGroup: "Back"},
	{Name: "Lat Pulldown", Category: "Cable", MuscleGroup: "Back"},
	{Name: "Close-Grip Lat Pulldown", Category: "Cable", MuscleGroup: "Back"},
	{Name: "Seated Cable Row", Category: "Cable", MuscleGroup: "Back"},
	{Name: "Straight-Arm Pulldown", Category: "Cable", MuscleGroup: "Back"},
	{Name: "Face Pull", Category: "Cable", MuscleGroup: "Back"},
	{Name: "Machine Row", Category: "Machine", MuscleGroup: "Back"},
	{Name: "Assisted Pull-Up", Category: "Machine", MuscleGroup: "Back"},
	{Name: "Smith Machine Row", Category: "Smith Machine", MuscleGroup: "Back"},

	// Shoulders
	{Name: "Overhead Press", Category: "Barbell", MuscleGroup: "Shoulders"},
	{Name: "Push Press", Category: "Barbell", MuscleGroup: "Shoulders"},
	{Name: "Landmine Press", Category: "Barbell", MuscleGroup: "Shoulders"},
	{Name: "Upright Row", Category: "Barbell", MuscleGroup: "Shoulders"},
	{Name: "Dumbbell Shoulder Press", Category: "Dumbbell", MuscleGroup: "Shoulders"},
	{Name: "Arnold Press", Category: "Dumbbell", MuscleGroup: "Shoulders"},
	{Name: "Lateral Raise", Category: "Dumbbell", MuscleGroup: "Shoulders"},
	{Name: "Front Raise", Category: "Dumbbell", MuscleGroup: "Shoulders"},
	{Name: "Rear Delt Fly", Category: "Dumbbell", MuscleGroup: "Shoulders"},
	{Name: "Cable Lateral Raise", Category: "Cable", MuscleGroup: "Shoulders"},
	{Name: "Machine Shoulder Press", Category: "Machine", MuscleGroup: "Shoulders"},
	{Name: "Reverse Pec Deck", Category: "Machine", MuscleGroup: "Shoulders"},
	{Name: "Smith Machine Shoulder Press", Category: "Smith Machine", MuscleGroup: "Shoulders"},

	// Glutes
	{Name: "Hip Thrust", Category: "Barbell", MuscleGroup: "Glutes"},
	{Name: "Barbell Glute Bridge", Category: "Barbell", MuscleGroup: "Glutes"},
	{Name: "Sumo Deadlift", Category: "Barbell", MuscleGroup: "Glutes"},
	{Name: "Glute Bridge", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Single-Leg Glute Bridge", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Frog Pump", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Donkey Kick", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Fire Hydrant", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Back Extension", Category: "Bodyweight", MuscleGroup: "Glutes"},
	{Name: "Cable Glute Kickback", Category: "Cable", MuscleGroup: "Glutes"},
	{Name: "Cable Pull-Through", Category: "Cable", MuscleGroup: "Glutes"},
	{Name: "Hip Abduction Machine", Category: "Machine", MuscleGroup: "Glutes"},
	{Name: "Hip Adduction Machine", Category: "Machine", MuscleGroup: "Glutes"},
	{Name: "Glute Kickback Machine", Category: "Machine", MuscleGroup: "Glutes"},
	{Name: "Step-Up", Category: "Dumbbell", MuscleGroup: "Glutes"},
	{Name: "Reverse Lunge", Category: "Dumbbell", MuscleGroup: "Glutes"},
	{Name: "Curtsy Lunge", Category: "Dumbbell", MuscleGroup: "Glutes"},
	{Name: "Sumo Squat", Category: "Dumbbell", MuscleGroup: "Glutes"},
	{Name: "Smith Machine Hip Thrust", Category: "Smith Machine", MuscleGroup: "Glutes"},
	{Name: "Kettlebell Swing", Category: "Kettlebell", MuscleGroup: "Glutes"},
	{Name: "Lateral Band Walk", Category: "Band", MuscleGroup: "Glutes"},
	{Name: "Banded Glute Bridge", Category: "Band", MuscleGroup: "Glutes"},

	// Legs
	{Name: "Barbell Squat", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Front Squat", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Box Squat", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Romanian Deadlift", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Stiff-Leg Deadlift", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Trap Bar Deadlift", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Good Morning", Category: "Barbell", MuscleGroup: "Legs"},
	{Name: "Bulgarian Split Squat", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Walking Lunge", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Lateral Lunge", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Goblet Squat", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Dumbbell Romanian Deadlift", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Single-Leg Romanian Deadlift", Category: "Dumbbell", MuscleGroup: "Legs"},
	{Name: "Leg Press", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Single-Leg Press", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Hack Squat", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Leg Curl", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Seated Leg Curl", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Leg Extension", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Calf Raise", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Seated Calf Raise", Category: "Machine", MuscleGroup: "Legs"},
	{Name: "Smith Machine Squat", Category: "Smith Machine", MuscleGroup: "Legs"},
	{Name: "Kettlebell Deadlift", Category: "Kettlebell", MuscleGroup: "Legs"},
	{Name: "Nordic Hamstring Curl", Category: "Bodyweight", MuscleGroup: "Legs"},
	{Name: "Sissy Squat", Category: "Bodyweight", MuscleGroup: "Legs"},
	{Name: "Pistol Squat", Category: "Bodyweight", MuscleGroup: "Legs"},
	{Name: "Wall Sit", Category: "Bodyweight", MuscleGroup: "Legs"},
	{Name: "Jump Squat", Category: "Bodyweight", MuscleGroup: "Legs"},
	{Name: "Single-Leg Calf Raise", Category: "Bodyweight", MuscleGroup: "Legs"},

	// Arms
	{Name: "Barbell Curl", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "EZ-Bar Curl", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "Preacher Curl", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "Skull Crusher", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "Close-Grip Bench Press", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "Reverse Curl", Category: "Barbell", MuscleGroup: "Arms"},
	{Name: "Dumbbell Curl", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Hammer Curl", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Incline Dumbbell Curl", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Concentration Curl", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Overhead Tricep Extension", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Tricep Kickback", Category: "Dumbbell", MuscleGroup: "Arms"},
	{Name: "Tricep Pushdown", Category: "Cable", MuscleGroup: "Arms"},
	{Name: "Cable Curl", Category: "Cable", MuscleGroup: "Arms"},
	{Name: "Rope Hammer Curl", Category: "Cable", MuscleGroup: "Arms"},
	{Name: "Overhead Cable Tricep Extension", Category: "Cable", MuscleGroup: "Arms"},
	{Name: "Machine Bicep Curl", Category: "Machine", MuscleGroup: "Arms"},
	{Name: "Machine Tricep Extension", Category: "Machine", MuscleGroup: "Arms"},
	{Name: "Tricep Dip", Category: "Bodyweight", MuscleGroup: "Arms"},
	{Name: "Diamond Push-Up", Category: "Bodyweight", MuscleGroup: "Arms"},
	{Name: "Bench Dip", Category: "Bodyweight", MuscleGroup: "Arms"},

	// Core
	{Name: "Plank", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Side Plank", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Hanging Leg Raise", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Lying Leg Raise", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Ab Wheel Rollout", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Russian Twist", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Sit-Up", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Decline Sit-Up", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Crunch", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Bicycle Crunch", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Mountain Climbers", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Dead Bug", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Bird Dog", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "V-Up", Category: "Bodyweight", MuscleGroup: "Core"},
	{Name: "Cable Crunch", Category: "Cable", MuscleGroup: "Core"},
	{Name: "Woodchop", Category: "Cable", MuscleGroup: "Core"},
	{Name: "Pallof Press", Category: "Cable", MuscleGroup: "Core"},
	{Name: "Machine Ab Crunch", Category: "Machine", MuscleGroup: "Core"},
	{Name: "Turkish Get-Up", Category: "Kettlebell", MuscleGroup: "Core"},
}
